base_config: ../config/xdeepfm_criteo_x4/
base_expid: xDeepFM_criteo_x4
dataset_id: criteo_x4
dataset_config:
    criteo_x4:
        data_format: h5
        data_root: '../data/'
        train_data: ../data/criteo_x4/train_sample.h5
        valid_data: ../data/criteo_x4/valid_sample.h5
        test_data: ../data/criteo_x4/test_sample.h5

tuner_space:
    embedding_dim: 16
    learning_rate: 1.e-3
    dnn_hidden_units: [[500,500,500,500,500],[1000,1000,1000,1000,1000]]
    cin_layer_units: [[64, 64, 64], [64, 64]]
    net_dropout: 0.2
    embedding_regularizer: [1.e-4, 1.e-3]
    batch_size: [10000]
    seed: 2019

